const arsMeteorites = [
    ["common_metals_meteors","kubejs:common_metals_meteors",50,0,"ars_nouveau:source_gem",[
        "minecraft:iron_ore",
        "minecraft:copper_ore",
        "minecraft:gold_ore",
        "thermal:silver_ore",
        "thermal:nickel_ore",
        "thermal:tin_ore",
        "redstone_chemical_elements:aluminum/aluminum_ore",
        "minecraft:stone"
    ],[15,6,7,8,7,7,20,30]],
    ["abyssal","kubejs:abyssal_meteors",100,3,"ars_nouveau:source_gem",[
        "minecraft:water",
        "alexscaves:bone_worms",
        "alexscaves:twilight_anemone",
        "alexscaves:dusk_anemone",
        "alexscaves:midnight_anemone",
        "alexscaves:mussel",
        "alexscaves:ping_pong_sponge",
        "alexscaves:tube_worm",
        "minecraft:water",
        "minecraft:oxidized_copper",
        "minecraft:wet_sponge",
        "minecraft:sea_lantern",
        "minecraft:deepslate_diamond_ore",
        "minecraft:deepslate",
        "alexscaves:muck",
        "minecraft:tuff",
        "alexscaves:abyssmarine"
    ],[25,2,1,1,1,5,10,5,10,5,3,5,2,3,10,2,10],[8,5,4,50,25,25]],
    ["aetherwork","kubejs:aetherworks_meteors",100,2,"ars_nouveau:source_gem",[
        "aetherworks:ore_aether",
        "aetherworks:suevite",
        "aetherworks:ore_aether",
        "aetherworks:suevite_cobble"
    ],[2,47,2,47]],
    ["alien","kubejs:alien_meteors",120,3,"ars_nouveau:source_gem",[
        "ae2:mysterious_cube",
        "ae2:flawless_budding_quartz",
        "ae2:flawed_budding_quartz",
        "ae2:chipped_budding_quartz",
        "ae2:damaged_budding_quartz",
        "ae2:quartz_block",
        "ae2:sky_stone_block",
        "ae2:fluix_block"
    ],[1,10,5,4,3,7,60,10],[6,2,30,70]],
    ["candy","kubejs:candy_meteors",100,3,"ars_nouveau:source_gem",[
        "alexscaves:candy_cane_pole",
        "alexscaves:licoroot",
        "alexscaves:stripped_candy_cane_block",
        "alexscaves:rock_candy_orange",
        "alexscaves:rock_candy_white",
        "alexscaves:rock_candy_lime",
        "alexscaves:rock_candy_light_blue",
        "alexscaves:rock_candy_yellow",
        "alexscaves:rock_candy_green",
        "alexscaves:vanilla_ice_cream",
        "alexscaves:chocolate_ice_cream",
        "alexscaves:sweetberry_ice_cream",
        "alexscaves:giant_sweetberry",
        "alexscaves:block_of_vanilla_frosting",
        "alexscaves:sugar_glass",
        "alexscaves:wafer_cookie_block",
        "alexscaves:block_of_polished_chocolate",
        "alexscaves:dough_block",
        "alexscaves:cookie_block",
        "alexscaves:gingerbread_block",
        "alexscaves:cake_layer",
        "alexscaves:block_of_chocolate",
        "alexscaves:block_of_frosted_chocolate"
    ],[3,5,5,3,3,3,3,3,3,3,3,3,3,4,3,5,5,10,5,7,6,7,5],[15,8,50,50]],
    ["magnet","kubejs:magnet_meteors",100,3,"ars_nouveau:source_gem",[
        "alexscaves:azure_neodymium_node",
        "alexscaves:azure_neodymium_pillar",
        "alexscaves:metal_swarf",
        "alexscaves:scarlet_neodymium_node",
        "alexscaves:scarlet_neodymium_pillar",
        "alexscaves:energized_galena_azure",
        "alexscaves:energized_galena_scarlet",
        "alexscaves:energized_galena_neutral",
        "alexscaves:galena_iron_ore",
        "alexscaves:galena",
        "minecraft:deepslate"
    ],[7,8,20,7,8,6,6,5,10,20,3],[5,6,50,50]],
    ["primitive","kubejs:primitive_meteors",100,3,"ars_nouveau:source_gem",[
        "minecraft:deepslate",
        "minecraft:packed_mud",
        "minecraft:sandstone",
        "alexscaves:limestone",
        "alexscaves:pewen_log",
        "alexscaves:fern_thatch",
        "alexscaves:pewen_branch",
        "alexscaves:subterranodon_egg",
        "minecraft:bone_block",
        "alexscaves:cycad",
        "alexscaves:amber",
        "minecraft:smooth_basalt",
        "alexscaves:flood_basalt",
        "alexscaves:primal_magma"
    ],[2,4,3,21,5,5,3,2,15,2,8,15,8,7],[4,7,3,30,40,30]]
]
ServerEvents.highPriorityData(event => {
    arsMeteorites.forEach(array => {
        if (array[3] === 0 || array[3] === 1 || array[3] === 2) {
            let meteorite = {
                input:array[1],
                source:array[2],
                model:array[3],
                catalysts:array[4],
                meteorites:array[5],
                weights:array[6]
            }
            let meteoritejson = JsonIO.of(meteorite)
            event.addJson(`arsmeteorites:meteorite_recipes/${array[0]}.json`,meteoritejson)
        }else if (array[3] === 3 || array[3] === 4) {
            let meteorite = {
                input:array[1],
                source:array[2],
                model:array[3],
                catalysts:array[4],
                meteorites:array[5],
                weights:array[6],
                layer:array[7]
            }
            let meteoritejson = JsonIO.of(meteorite)
            event.addJson(`arsmeteorites:meteorite_recipes/${array[0]}.json`,meteoritejson)
        }
    })
})