const firstch = ["1k","4k","16k"]
ServerEvents.recipes(event => {
event.custom({
    "type":"ae2:inscriber",
    "ingredients":{"bottom":{"item":"ae2:annihilation_core"},
    "middle":{"item":"minecraft:chest"},
    "top":{"item":"ae2:formation_core"}},
    "mode":"press",
    "result":{"item":"kubejs:item_digital_transducer"}
})
event.custom({
    "type":"ae2:inscriber",
    "ingredients":{"bottom":{"item":"ae2:annihilation_core"},
    "middle":{"item":"embers:fluid_vessel"},
    "top":{"item":"ae2:formation_core"}},
    "mode":"press",
    "result":{"item":"kubejs:fluid_digital_transducer"}
})
event.custom({
    "type":"ae2:inscriber",
    "ingredients":{"bottom":{"item":"ae2:annihilation_core"},
    "middle":{"item":"botania:mana_pool"},
    "top":{"item":"ae2:formation_core"}},
    "mode":"press",
    "result":{"item":"kubejs:mana_digital_transducer"}
})
event.custom({
    "type":"ae2:inscriber",
    "ingredients":{"bottom":{"item":"ae2:annihilation_core"},
    "middle":{"item":"ars_nouveau:source_jar"},
    "top":{"item":"ae2:formation_core"}},
    "mode":"press",
    "result":{"item":"kubejs:source_digital_transducer"}
})
event.custom({
    "type":"ae2:inscriber",
    "ingredients":{"bottom":{"item":"ae2:annihilation_core"},
    "middle":{"item":"ae2:energy_cell"},
    "top":{"item":"ae2:formation_core"}},
    "mode":"press",
    "result":{"item":"kubejs:energy_digital_transducer"}
})
    firstch.forEach((
        firstch => {
            event.custom({
                "type":"ae2:inscriber",
                "ingredients":{"bottom":{"item":`kubejs:${firstch}_storage_circuits_etched_substrate`},
                "middle":{"item":"tconstruct:queens_slime_ingot"},
                "top":{"item":"kubejs:item_digital_transducer"}},
                "mode":"press",
                "result":{"item":`ae2:cell_component_${firstch}`}
            })
            event.custom({
                "type":"ae2:inscriber",
                "ingredients":{"bottom":{"item":`kubejs:${firstch}_storage_circuits_etched_substrate`},
                "middle":{"item":"tconstruct:queens_slime_ingot"},
                "top":{"item":"kubejs:fluid_digital_transducer"}},
                "mode":"press",
                "result":{"item":`kubejs:${firstch}_fluid_cell`}
            })
            event.custom({
                "type":"ae2:inscriber",
                "ingredients":{"bottom":{"item":`kubejs:${firstch}_storage_circuits_etched_substrate`},
                "middle":{"item":"tconstruct:queens_slime_ingot"},
                "top":{"item":"kubejs:mana_digital_transducer"}},
                "mode":"press",
                "result":{"item":`kubejs:${firstch}_mana_cell`}
            })
            event.custom({
                "type":"ae2:inscriber",
                "ingredients":{"bottom":{"item":`kubejs:${firstch}_storage_circuits_etched_substrate`},
                "middle":{"item":"tconstruct:queens_slime_ingot"},
                "top":{"item":"kubejs:energy_digital_transducer"}},
                "mode":"press",
                "result":{"item":`appflux:core_${firstch}`}
            })
            event.custom({
                "type":"ae2:inscriber",
                "ingredients":{"bottom":{"item":`kubejs:${firstch}_storage_circuits_etched_substrate`},
                "middle":{"item":"tconstruct:queens_slime_ingot"},
                "top":{"item":"kubejs:source_digital_transducer"}},
                "mode":"press",
                "result":{"item":`kubejs:${firstch}_source_cell`}
            })



            event.custom({
                "type":"ae2:inscriber",
                "ingredients":{"bottom":{"item":"ae2:item_cell_housing"},
                "middle":{"item":"tinkersinnovation:slimton_ingot"},
                "top":{"item":`ae2:cell_component_${firstch}`}},
                "mode":"press",
                "result":{"item":`ae2:item_storage_cell_${firstch}`}
            })
            event.custom({
                "type":"ae2:inscriber",
                "ingredients":{"bottom":{"item":"ae2:fluid_cell_housing"},
                "middle":{"item":"tinkersinnovation:slimton_ingot"},
                "top":{"item":`kubejs:${firstch}_fluid_cell`}},
                "mode":"press",
                "result":{"item":`ae2:fluid_storage_cell_${firstch}`}
            })
            event.custom({
                "type":"ae2:inscriber",
                "ingredients":{"bottom":{"item":"arseng:source_cell_housing"},
                "middle":{"item":"tinkersinnovation:slimton_ingot"},
                "top":{"item":`kubejs:${firstch}_source_cell`}},
                "mode":"press",
                "result":{"item":`arseng:source_storage_cell_${firstch}`}
            })
            event.custom({
                "type":"ae2:inscriber",
                "ingredients":{"bottom":{"item":"appflux:fe_cell_housing"},
                "middle":{"item":"tinkersinnovation:slimton_ingot"},
                "top":{"item":`appflux:core_${firstch}`}},
                "mode":"press",
                "result":{"item":`appflux:fe_${firstch}_cell`}
            })
            event.custom({
                "type":"ae2:inscriber",
                "ingredients":{"bottom":{"item":"appbot:mana_cell_housing"},
                "middle":{"item":"tinkersinnovation:slimton_ingot"},
                "top":{"item":`kubejs:${firstch}_mana_cell`}},
                "mode":"press",
                "result":{"item":`appbot:mana_storage_cell_${firstch}`}
            })
        }
    ))
})