/**
 * Tinkers' Elemental - Trial Customization Type Definitions
 * Auto-generated by TinkersElemental mod
 *
 * This file provides TypeScript type definitions for the trial customization API.
 * Place this file in your kubejs directory for better IDE support.
 */

declare namespace TinkersElemental {
    namespace trials {
        /**
         * Simple trial customization
         * Modify event type and target value for existing trials
         *
         * @param trialId The trial ID (e.g., 'tinkerselemental:fire_trial')
         * @param eventType Event type: 'attack', 'mining', 'kill', etc.
         * @param targetValue Number of events needed to complete the trial
         * @param description Custom description in Chinese
         * @param tooltipHint Custom tooltip hint for Shift display (optional)
         *
         * @example
         * ```typescript
         * TinkersElemental.trials.customize(
         *     'tinkerselemental:fire_trial',
         *     'attack',
         *     30,
         *     '使用火元素武器攻击敌人',
         *     '用火元素武器攻击30次'
         * )
         * ```
         */
        function customize(
            trialId: string,
            eventType: string,
            targetValue: number,
            description: string,
            tooltipHint?: string
        ): void;

        /**
         * Clear all trial customizations (useful for reloading)
         */
        function clear(): void;
    }
}

/**
 * ElementalEvents namespace for KubeJS event listeners
 */
declare namespace ElementalEvents {
    /**
     * Trial register event - fired when getting trial metadata
     * Use this event to define trial descriptions and tooltip hints
     *
     * @param callback Event handler function
     *
     * @example
     * ```typescript
     * // Register trial description
     * ElementalEvents.trialRegister(event => {
     *     if (event.getTrialId() !== 'tinkerselemental:nether_ceiling_trial') return
     *
     *     event.setDescription('到达地狱最顶层（Y >= 127）')
     *     event.setTooltipHint('前往地狱并到达Y=127的高度')
     * })
     * ```
     */
    function trialRegister(callback: (event: TrialRegisterEventJS) => void): void;

    /**
     * Trial check event - fired when checking if a trial is completed
     * Use this event to define custom completion conditions
     *
     * @param callback Event handler function
     *
     * @example
     * ```typescript
     * // Check if player reached Nether ceiling
     * ElementalEvents.trialCheck(event => {
     *     if (event.getTrialId() !== 'tinkerselemental:nether_ceiling_trial') return
     *
     *     let player = event.getPlayer()
     *     if (!player) return
     *
     *     let inNether = player.level.dimension === 'minecraft:the_nether'
     *     let atCeiling = player.y >= 127
     *
     *     if (inNether && atCeiling) {
     *         event.setCompleted(true)
     *     }
     * })
     * ```
     */
    function trialCheck(callback: (event: TrialCheckEventJS) => void): void;
}

/**
 * Trial register event object
 */
interface TrialRegisterEventJS {
    /**
     * Get the trial ID as string
     */
    getTrialId(): string;

    /**
     * Set the trial description (shown in tooltip)
     *
     * @param description Description text in Chinese
     */
    setDescription(description: string): void;

    /**
     * Set the tooltip hint (shown when holding Shift)
     * If not set, uses the description
     *
     * @param tooltipHint Tooltip hint text
     */
    setTooltipHint(tooltipHint: string): void;
}

/**
 * Trial check event object
 */
interface TrialCheckEventJS {
    /**
     * Get the tool being used
     */
    getTool(): any; // ToolStack from Tinkers' Construct

    /**
     * Get the trial ID as string
     */
    getTrialId(): string;

    /**
     * Get the player (may be null in some contexts like tooltips)
     */
    getPlayer(): any; // Player from Minecraft

    /**
     * Get the raw event data (if any)
     */
    getEventData(): any;

    /**
     * Set the trial completion result
     * Call this to mark the trial as completed or not
     *
     * @param completed true if trial is completed, false otherwise
     */
    setCompleted(completed: boolean): void;
}

// Export for module usage
export {};
