ServerEvents.recipes(event => {
    event.replaceInput({
        input:"minecraft:redstone_torch",
        output:"sophisticatedstorage:chest"
    },"minecraft:redstone_torch","minecraft:chest")
    event.replaceInput({
        input:"minecraft:redstone_torch",
        output:"sophisticatedstorage:barrel"
    },"minecraft:redstone_torch","minecraft:barrel")
    event.replaceInput({
        output:"minecraft:compass"
    },"minecraft:redstone","kubejs:simple_basic_component")
    event.replaceInput({
        output:"embers:copper_charger"
    },"minecraft:copper_ingot","kubejs:dawnstone_machine_frame")
    event.replaceInput({
        output:"embers:pressure_refinery"
    },"minecraft:copper_block","kubejs:dawnstone_machine_frame")
    event.replaceInput({
        output:"embers:pressure_refinery"
    },"embers:dawnstone_ingot","embers:ember_activator")
    event.replaceInput({
        output:"embers:inferno_forge"
    },"minecraft:copper_block","kubejs:dawnstone_machine_frame")
    event.replaceInput({
        output:"embers:dawnstone_anvil"
    },"embers:dawnstone_ingot","kubejs:dawnstone_machine_frame")
    event.replaceInput({
        output:"embers:crystal_cell"
    },"minecraft:copper_block","kubejs:dawnstone_machine_frame")
    event.replaceInput({
        output:"embers:ember_relay"
    },"thermal:iron_plate","kubejs:simple_basic_component")
    event.replaceInput({
        output:"embers:beam_splitter"
    },"thermal:iron_plate","embers:ember_relay")
    event.replaceInput({
        output:"embers:copper_cell"
    },"minecraft:copper_block","kubejs:caminite_machine_frame")
    event.replaceInput({
        output:"ars_nouveau:imbuement_chamber"
    },"ars_nouveau:archwood_planks","kubejs:reinforced_archwood_planks")
    event.replaceInput({
        output:"ars_nouveau:imbuement_chamber"
    },"minecraft:gold_ingot","kubejs:ultra_neodymium_ingot")
    event.replaceInput({
        output:"ars_nouveau:source_gem",
        input:"minecraft:lapis_lazuli"
    },"minecraft:lapis_lazuli","kubejs:source_matter_base")
    event.replaceInput({
        output:"embers:excavation_buckets"
    },"minecraft:iron_ingot","kubejs:caminite_machine_frame")
    event.replaceInput({
        output:"pipez:item_pipe"
    },"minecraft:dropper","embers:item_pipe")
    event.replaceInput({
        output:"pipez:fluid_pipe"
    },"minecraft:bucket","embers:fluid_pipe")
    event.replaceInput({
        output:"thermal:fluid_duct"
    },"#forge:ingots/bronze","embers:fluid_pipe")
    event.replaceInput({
        output:"thermal:fluid_duct_windowed"
    },"#forge:ingots/bronze","embers:fluid_pipe")
    event.replaceInput({
        output:"laserio:card_item"
    },"minecraft:gold_nugget","pipez:item_pipe")
    event.replaceInput({
        output:"laserio:card_fluid"
    },"minecraft:gold_nugget","pipez:fluid_pipe")
    event.replaceInput({
        output:"embers:ignem_reactor"
    },"embers:caminite_bricks","kubejs:burn_sun_block")
    event.replaceInput({
        output:"apotheosis:seashelf"
    },"minecraft:prismarine_bricks","alexscaves:mussel")
    event.replaceInput({
        output:"minecraft:enchanting_table"
    },"minecraft:obsidian","apotheosis:hellshelf")
    event.replaceInput({
        output:"minecraft:enchanting_table"
    },"minecraft:diamond","apotheosis:seashelf")
    event.replaceInput({
        output:"minecraft:enchanting_table"
    },"minecraft:book","apotheosis:dormant_deepshelf")
    event.replaceInput({
        output:"embers:heat_insulation"
    },"minecraft:copper_block","kubejs:dawnstone_machine_frame")
    event.replaceInput({
        output:"ars_nouveau:air_essence"
    },"ars_nouveau:source_gem","kubejs:essence_base")
    event.replaceInput({
        output:"ars_nouveau:fire_essence"
    },"ars_nouveau:source_gem","kubejs:essence_base")
    event.replaceInput({
        output:"ars_nouveau:conjuration_essence"
    },"ars_nouveau:source_gem","kubejs:essence_base")
    event.replaceInput({
        output:"ars_nouveau:water_essence"
    },"ars_nouveau:source_gem","kubejs:essence_base")
    event.replaceInput({
        output:"ars_nouveau:abjuration_essence"
    },"ars_nouveau:source_gem","kubejs:essence_base")
    event.replaceInput({
        output:"ars_nouveau:manipulation_essence"
    },"ars_nouveau:source_gem","kubejs:essence_base")
    event.replaceInput({
        output:"ars_nouveau:earth_essence"
    },"ars_nouveau:source_gem","kubejs:essence_base")
    event.replaceInput({
        output:"mob_grinding_utils:jumbo_tank"
    },"mob_grinding_utils:tank","portabletanks:ultimate_portable_tank")
    event.replaceInput({
        output:"functionalstorage:fluid_1"
    },"minecraft:bucket","mob_grinding_utils:jumbo_tank")
    event.replaceInput({
        output:"functionalstorage:fluid_2"
    },"minecraft:bucket","mob_grinding_utils:jumbo_tank")
    event.replaceInput({
        output:"functionalstorage:fluid_4"
    },"minecraft:bucket","mob_grinding_utils:jumbo_tank")
    event.replaceInput({
        output:"aetherworks:aetheriometer"
    },"embers:ember_jar","kubejs:source_netherite_component")
    event.replaceInput({
        output:"aetherworks:heat_dial"
    },"minecraft:paper","kubejs:source_netherite_component")
    event.replaceInput({
        output:"aetherworks:prism"
    },"embers:archaic_circuit","kubejs:aetherworks_machine_frame")
    event.replaceInput({
        output:"aetherworks:aether_prism_controller_matrix"
    },"embers:intelligent_apparatus","kubejs:aetherworks_machine_frame")
    event.replaceInput({
        output:"aetherworks:aether_forge"
    },"embers:caminite_bricks","kubejs:aetherworks_machine_frame")
    event.replaceInput({
        output:"aetherworks:aether_forge"
    },"minecraft:copper_block","aetherworks:aether_amalgam")
    event.replaceInput({
        output:"aetherworks:forge_heater"
    },"#forge:plates/copper","kubejs:aetherworks_machine_frame")
    event.replaceInput({
        output:"aetherworks:forge_cooler"
    },"embers:archaic_circuit","kubejs:aetherworks_machine_frame")
    event.replaceInput({
        output:"aetherworks:forge_anvil"
    },"embers:dawnstone_block","kubejs:aetherworks_machine_frame")
    event.replaceInput({
        output:"aetherworks:forge_metal_former"
    },"embers:ash","kubejs:aetherworks_machine_frame")
    event.replaceInput({
        output:"ae2:inscriber"
    },"minecraft:sticky_piston","embers:automatic_hammer")
    event.replaceInput({
        output:"ae2:inscriber"
    },"minecraft:copper_ingot","kubejs:source_gem_steel_machine_frame")
    event.replaceInput({
        output:"ae2:controller"
    },"ae2:smooth_sky_stone_block","kubejs:complex_processing_computer")
    event.replaceInput({
        output:"ae2:controller"
    },"ae2:engineering_processor","kubejs:source_gem_steel_machine_frame")
})