ServerEvents.recipes(event => {
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["iceandfire:stymphalian_bird_dagger", "alexscaves:limestone_spear", "embers:tyrfing", "cataclysm:black_steel_sword","iceandfire:silver_sword"], // input items
        "kubejs:metal_essence", // reagent
        "kubejs:swords_essence", // output
        3000 // source cost
        // true // keep nbt of reagent, think like a smithing recipe
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["forbidden_arcanus:bat_wing","minecraft:feather","alexsmobs:emu_feather","ars_nouveau:wilden_wing","alexsmobs:cockroach_wing"],
        "ars_nouveau:air_essence",
        "kubejs:sky_essence",
        3000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["minecraft:glow_berries","iceandfire:lightning_lily","biomeswevegone:cypress_sapling","alexscaves:pewen_branch","#botania:mystical_flowers"],
        "kubejs:tree_essence",
        "kubejs:lush_forests_essence",
        3000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["tconstruct:blazing_bone","minecraft:fire_charge","cataclysm:dying_ember","tconstruct:ichor_slime_crystal","alexscaves:primal_magma"],
        "ars_nouveau:fire_essence",
        "kubejs:inferno_essence",
        3000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["alexscaves:floater","alexscaves:pearl","alexscaves:sea_glass_shards","minecraft:prismarine_crystals","cataclysm:lionfish"],
        "ars_nouveau:water_essence",
        "kubejs:vast_ocean_essence",
        3000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["cataclysm:ancient_metal_ingot","embers:archaic_brick","goety:snowy_highrock_bricks","alexscaves:muck","alexscaves:dough_block"],
        "ars_nouveau:earth_essence",
        "kubejs:range_mountains_essence",
        3000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["minecraft:gold_ingot","minecraft:gold_nugget","minecraft:gold_nugget","minecraft:gold_nugget","minecraft:gold_nugget"],
        "kubejs:forged_nether_alloy_plate",
        "kubejs:calibrated_alloy_core",
        500
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["alexsmobs:cockroach_wing","alexsmobs:cockroach_ootheca"],
        "minecraft:egg",
        "alexsmobs:spawn_egg_cockroach",
        1000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["alexsmobs:emu_feather","alexsmobs:emu_feather","alexsmobs:emu_feather"],
        "minecraft:egg",
        "alexsmobs:spawn_egg_emu",
        1000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["iceandfire:wither_shard","iceandfire:wither_shard","iceandfire:wither_shard","minecraft:feather"],
        "minecraft:egg",
        "aether:cockatrice_spawn_egg",
        1000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["cataclysm:dying_ember","cataclysm:dying_ember","cataclysm:dying_ember"],
        "minecraft:egg",
        "cataclysm:ignited_berserker_spawn_egg",
        1000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["cataclysm:lionfish"]
        ,"minecraft:egg",
        "cataclysm:lionfish_spawn_egg",
        1000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["alexscaves:floater","alexscaves:floater","alexscaves:floater"],
        "minecraft:egg",
        "alexscaves:spawn_egg_gossamer_worm",
        1000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["cataclysm:ancient_metal_ingot","minecraft:bone","minecraft:bone"],
        "minecraft:egg",
        "cataclysm:koboleton_spawn_egg",
        1000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["iceandfire:stymphalian_bird_feather","iceandfire:stymphalian_bird_feather","iceandfire:stymphalian_bird_feather"],
        "minecraft:egg",
        "iceandfire:spawn_egg_stymphalian_bird",
        1000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["forbidden_arcanus:bat_wing","forbidden_arcanus:bat_wing","forbidden_arcanus:bat_wing"],
        "minecraft:egg",
        "minecraft:bat_spawn_egg",
        1000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["ars_nouveau:wilden_wing","ars_nouveau:wilden_wing","ars_nouveau:wilden_wing"],
        "minecraft:egg",
        "ars_nouveau:wilden_stalker_se",
        1000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["cataclysm:black_steel_ingot","cataclysm:black_steel_ingot","cataclysm:black_steel_ingot","cataclysm:black_steel_sword"],
        "minecraft:egg",
        "cataclysm:draugr_spawn_egg",
        1000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["thermal:gunpowder_block","minecraft:gold_block","minecraft:gold_block","ars_nouveau:source_gem_block","ars_nouveau:source_gem_block"],
        "kubejs:source_gem_steel_machine_frame",
        "ars_nouveau:basic_spell_turret",
        10000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["kubejs:range_mountains_essence","kubejs:range_mountains_essence","kubejs:range_mountains_essence","kubejs:range_mountains_essence"],
        "minecraft:netherite_ingot",
        "arsmeteorites:ritual_conjure_meteorites",
        5000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["kubejs:sky_essence","kubejs:sky_essence","kubejs:sky_essence","kubejs:sky_essence","divinerpg:aqua_ball","divinerpg:aqua_ball","divinerpg:aqua_ball","divinerpg:aqua_ball"],
        "kubejs:source_gem_steel_machine_frame",
        "kubejs:aetherworks_machine_frame",
        10000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["kubejs:source_gem_steel_plate","kubejs:source_gem_steel_plate","kubejs:source_gem_steel_plate","kubejs:source_gem_steel_plate","thermal:netherite_gear","thermal:netherite_gear"],
        "kubejs:calibrated_alloy_core",
        "kubejs:source_netherite_component",
        10000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["kubejs:sky_essence","kubejs:swords_essence","kubejs:inferno_essence","kubejs:vast_ocean_essence","kubejs:lush_forests_essence","kubejs:range_mountains_essence"],
        "ars_nouveau:source_gem",
        "kubejs:nouveau_essence",
        10000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        [Item.of('avaritia:singularity', '{Id:"kubejs:nouveau_essence_singularity"}').weakNBT(),Item.of('avaritia:singularity', '{Id:"kubejs:ember_essence_singularity"}').weakNBT(),Item.of('avaritia:singularity', '{Id:"kubejs:nouveau_essence_singularity"}').weakNBT(),Item.of('avaritia:singularity', '{Id:"kubejs:ember_essence_singularity"}').weakNBT(),Item.of('avaritia:singularity', '{Id:"kubejs:nouveau_essence_singularity"}').weakNBT(),Item.of('avaritia:singularity', '{Id:"kubejs:ember_essence_singularity"}').weakNBT(),Item.of('avaritia:singularity', '{Id:"kubejs:nouveau_essence_singularity"}').weakNBT(),Item.of('avaritia:singularity', '{Id:"kubejs:ember_essence_singularity"}').weakNBT(),Item.of('avaritia:singularity', '{Id:"kubejs:nouveau_essence_singularity"}').weakNBT(),Item.of('avaritia:singularity', '{Id:"kubejs:ember_essence_singularity"}').weakNBT()],
        Item.of('packagedauto:volume_package','{Fluid:{Amount:50000,FluidName:"kubejs:molten_ultra_neodymium"},Type:"minecraft:fluid"}').weakNBT(),
        Item.of('packagedauto:volume_package','{Fluid:{Amount:1000,FluidName:"kubejs:history_adhesive"},Type:"minecraft:fluid"}'),
        10000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["kubejs:source_netherite_component","kubejs:source_netherite_component","kubejs:source_netherite_component","kubejs:source_netherite_component"],
        "kubejs:4k_storage_circuits_etched_substrate",
        "kubejs:16k_storage_circuits_etched_substrate",
        50000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["rootsclassic:infernal_bulb","kubejs:inferno_bulb_seed"],
        "kubejs:inferno_essence",
        "2x kubejs:refine_inferno_bulb",
        10000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["kubejs:wildroot_seed","twilightforest:root_strand","rootsclassic:old_root","minecraft:rooted_dirt","twilightforest:liveroot_block","aether:skyroot_log"],
        "kubejs:aetherwork_inferno_bulb",
        "kubejs:entangle_aura_root",
        10000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["kubejs:root_wrapped_invar_ingot","kubejs:root_wrapped_invar_ingot","kubejs:root_wrapped_invar_plate","kubejs:root_wrapped_invar_plate","kubejs:root_wrapped_invar_plate","kubejs:root_wrapped_invar_plate"],
        "kubejs:aetherworks_machine_frame",
        "kubejs:root_wrapped_invar_machine_frame",
        100000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["rootsclassic:old_root","rootsclassic:old_root","rootsclassic:verdant_sprig","rootsclassic:verdant_sprig","rootsclassic:infernal_bulb","rootsclassic:infernal_bulb","rootsclassic:dragons_eye","rootsclassic:dragons_eye","goety:highrock_bricks","kubejs:range_mountains_essence","kubejs:lush_forests_essence","aether:sentry_stone"],
        "kubejs:root_wrapped_invar_machine_frame",
        "rootsclassic:altar",
        100000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["kubejs:nouveau_essence","kubejs:ember_essence","thermal:steel_block","thermal:steel_block","thermal:steel_block","thermal:steel_block","thermal:steel_block","thermal:steel_block"],
        "kubejs:aetherworks_machine_frame",
        "avaritia:neutron_compressor",
        100000
    )
    event.recipes.ars_nouveau.enchanting_apparatus(
        ["kubejs:lush_forests_essence","kubejs:lush_forests_essence","kubejs:lush_forests_essence","biomeswevegone:blueberries","biomeswevegone:oddion_bulb","minecraft:beetroot"],
        "ars_nouveau:magebloom_crop",
        "kubejs:aubergine_seed",
        5000
    )
})