/**
 * Auto-generated type definitions for Tinkers' Elemental Events
 * Generated by ElementalEventTypeGenerator
 * DO NOT EDIT MANUALLY
 */

// ElementalEvents namespace
declare namespace ElementalEvents {
    // Element effect events
    function elementAttack(callback: (event: ElementAttackEvent) => void): void;
    function elementMining(callback: (event: ElementMiningEvent) => void): void;
    function elementRightClick(callback: (event: ElementRightClickEvent) => void): void;

    // Reaction events
    function elementReaction(callback: (event: ElementReactionEvent) => void): void;

    // Trial events
    function trialProgress(callback: (event: TrialProgressEvent) => void): void;
    function trialComplete(callback: (event: TrialCompleteEvent) => void): void;

    // Skill events
    function skillActivate(callback: (event: SkillActivateEvent) => void): void;
}

interface ElementAttackEvent {
    getTool(): any;
    getUser(): PlayerJS | null;
    getTarget(): EntityJS | null;
    getElementId(): string;
    getElementLevel(): number;
}

interface ElementMiningEvent {
    getTool(): any;
    getUser(): PlayerJS;
    getElementId(): string;
    getElementLevel(): number;
}

interface ElementRightClickEvent {
    getTool(): any;
    getUser(): PlayerJS;
    getElementId(): string;
    getElementLevel(): number;
}

interface ElementReactionEvent {
    getTool(): any;
    getUser(): PlayerJS | null;
    getTarget(): EntityJS | null;
    getElement1Id(): string;
    getElement2Id(): string;
    getCombinedLevel(): number;
}

interface TrialProgressEvent {
    getTool(): any;
    getUser(): PlayerJS;
    getTrialId(): string;
    getProgress(): number;
    getTargetProgress(): number;
}

interface TrialCompleteEvent {
    getTool(): any;
    getUser(): PlayerJS;
    getTrialId(): string;
}

interface SkillActivateEvent {
    getTool(): any;
    getUser(): PlayerJS | null;
    getTarget(): EntityJS | null;
    getSkillId(): string;
}

// Re-export PlayerJS and EntityJS for convenience
interface PlayerJS {
    readonly name: string;
    heal(amount: number): void;
    hurt(source: string, amount: number): boolean;
    addEffect(effect: string, duration: number, amplifier: number): void;
    blockPosition(): { x: number; y: number; z: number };
    position(): { x: number; y: number; z: number };
    level: any;
}

interface EntityJS {
    hurt(source: string, amount: number): boolean;
    setOnFire(seconds: number): void;
    clearFire(): void;
    knockback(strength: number, xRatio: number, zRatio: number): void;
    addEffect(effect: string, duration: number, amplifier: number): void;
    blockPosition(): { x: number; y: number; z: number };
    position(): { x: number; y: number; z: number };
    level: any;
}
